// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Website_QuanLyKhoHangThucPham.Data;

#nullable disable

namespace Website_QuanLyKhoHangThucPham.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Website_QuanLyKhoHangThucPham.Models.AppPermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Controller")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("PermissionKey")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.ToTable("AppPermissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Action = "Index",
                            Controller = "Category",
                            DisplayName = "Xem danh muc",
                            PermissionKey = "Category.Index"
                        },
                        new
                        {
                            Id = 2,
                            Action = "Create",
                            Controller = "Category",
                            DisplayName = "Tao danh muc",
                            PermissionKey = "Category.Create"
                        },
                        new
                        {
                            Id = 3,
                            Action = "Edit",
                            Controller = "Category",
                            DisplayName = "Sua danh muc",
                            PermissionKey = "Category.Edit"
                        },
                        new
                        {
                            Id = 4,
                            Action = "Index",
                            Controller = "Supplier",
                            DisplayName = "Xem NCC",
                            PermissionKey = "Supplier.Index"
                        },
                        new
                        {
                            Id = 5,
                            Action = "Create",
                            Controller = "Supplier",
                            DisplayName = "Tao NCC",
                            PermissionKey = "Supplier.Create"
                        },
                        new
                        {
                            Id = 6,
                            Action = "Index",
                            Controller = "Product",
                            DisplayName = "Xem san pham",
                            PermissionKey = "Product.Index"
                        },
                        new
                        {
                            Id = 7,
                            Action = "Create",
                            Controller = "Product",
                            DisplayName = "Tao san pham",
                            PermissionKey = "Product.Create"
                        },
                        new
                        {
                            Id = 8,
                            Action = "Edit",
                            Controller = "Product",
                            DisplayName = "Sua san pham",
                            PermissionKey = "Product.Edit"
                        },
                        new
                        {
                            Id = 9,
                            Action = "Index",
                            Controller = "ImportReceipt",
                            DisplayName = "Xem phieu nhap",
                            PermissionKey = "ImportReceipt.Index"
                        },
                        new
                        {
                            Id = 10,
                            Action = "Create",
                            Controller = "ImportReceipt",
                            DisplayName = "Lap phieu nhap",
                            PermissionKey = "ImportReceipt.Create"
                        },
                        new
                        {
                            Id = 11,
                            Action = "Index",
                            Controller = "ExportRequest",
                            DisplayName = "Xem yeu cau xuat",
                            PermissionKey = "ExportRequest.Index"
                        },
                        new
                        {
                            Id = 12,
                            Action = "Create",
                            Controller = "ExportRequest",
                            DisplayName = "Tao yeu cau xuat",
                            PermissionKey = "ExportRequest.Create"
                        },
                        new
                        {
                            Id = 13,
                            Action = "Process",
                            Controller = "ExportRequest",
                            DisplayName = "Duyet xuat kho",
                            PermissionKey = "ExportRequest.Process"
                        },
                        new
                        {
                            Id = 14,
                            Action = "Index",
                            Controller = "AuditLog",
                            DisplayName = "Xem audit log",
                            PermissionKey = "AuditLog.Index"
                        },
                        new
                        {
                            Id = 15,
                            Action = "History",
                            Controller = "Payment",
                            DisplayName = "Xem lich su thanh toan",
                            PermissionKey = "Payment.History"
                        });
                });

            modelBuilder.Entity("Website_QuanLyKhoHangThucPham.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Website_QuanLyKhoHangThucPham.Models.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("Website_QuanLyKhoHangThucPham.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Rau cu tuoi"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Trai cay"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Thit & Hai san"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Sua & San pham tu sua"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Do dong hop"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Ngu coc & Hat"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Do uong"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Gia vi & Nuoc cham"
                        });
                });

            modelBuilder.Entity("Website_QuanLyKhoHangThucPham.Models.ExportRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProcessedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("RequestCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RequestedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedById");

                    b.HasIndex("RequestCode")
                        .IsUnique();

                    b.HasIndex("RequestedById");

                    b.ToTable("ExportRequests");
                });

            modelBuilder.Entity("Website_QuanLyKhoHangThucPham.Models.ExportRequestDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ActualQuantity")
                        .HasColumnType("int");

                    b.Property<int>("ExportRequestId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int?>("ProductId1")
                        .HasColumnType("int");

                    b.Property<int>("RequestedQuantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExportRequestId");

                    b.HasIndex("ProductId");

                    b.HasIndex("ProductId1");

                    b.ToTable("ExportRequestDetails");
                });

            modelBuilder.Entity("Website_QuanLyKhoHangThucPham.Models.ImportReceipt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ConfirmedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CreatedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("ImportDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ReceiptCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.Property<int?>("SupplierId1")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ConfirmedById");

                    b.HasIndex("CreatedById");

                    b.HasIndex("ReceiptCode")
                        .IsUnique();

                    b.HasIndex("SupplierId");

                    b.HasIndex("SupplierId1");

                    b.ToTable("ImportReceipts");
                });

            modelBuilder.Entity("Website_QuanLyKhoHangThucPham.Models.ImportReceiptDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BatchCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ImportReceiptId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ManufactureDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int?>("ProductId1")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ImportReceiptId");

                    b.HasIndex("ProductId");

                    b.HasIndex("ProductId1");

                    b.ToTable("ImportReceiptDetails");
                });

            modelBuilder.Entity("Website_QuanLyKhoHangThucPham.Models.InventoryBatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BatchCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ManufactureDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReceivedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BatchCode")
                        .IsUnique();

                    b.HasIndex("ProductId");

                    b.ToTable("InventoryBatches");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BatchCode = "B-SP001-A",
                            ExpiryDate = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            ManufactureDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = 1,
                            Quantity = 150,
                            ReceivedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            BatchCode = "B-SP002-A",
                            ExpiryDate = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            ManufactureDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = 2,
                            Quantity = 80,
                            ReceivedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            BatchCode = "B-SP003-A",
                            ExpiryDate = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            ManufactureDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = 3,
                            Quantity = 120,
                            ReceivedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            BatchCode = "B-SP004-A",
                            ExpiryDate = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            ManufactureDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = 4,
                            Quantity = 60,
                            ReceivedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            BatchCode = "B-SP005-A",
                            ExpiryDate = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            ManufactureDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = 5,
                            Quantity = 90,
                            ReceivedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 6,
                            BatchCode = "B-SP006-A",
                            ExpiryDate = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            ManufactureDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = 6,
                            Quantity = 50,
                            ReceivedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 7,
                            BatchCode = "B-SP007-A",
                            ExpiryDate = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            ManufactureDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = 7,
                            Quantity = 30,
                            ReceivedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 8,
                            BatchCode = "B-SP008-A",
                            ExpiryDate = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            ManufactureDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = 8,
                            Quantity = 40,
                            ReceivedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 9,
                            BatchCode = "B-SP009-A",
                            ExpiryDate = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            ManufactureDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = 9,
                            Quantity = 200,
                            ReceivedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 10,
                            BatchCode = "B-SP010-A",
                            ExpiryDate = new DateTime(2026, 9, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            ManufactureDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = 10,
                            Quantity = 300,
                            ReceivedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 11,
                            BatchCode = "B-SP011-A",
                            ExpiryDate = new DateTime(2026, 9, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            ManufactureDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = 11,
                            Quantity = 100,
                            ReceivedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 12,
                            BatchCode = "B-SP012-A",
                            ExpiryDate = new DateTime(2026, 9, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            ManufactureDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = 12,
                            Quantity = 150,
                            ReceivedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 13,
                            BatchCode = "B-SP013-A",
                            ExpiryDate = new DateTime(2026, 9, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            ManufactureDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = 13,
                            Quantity = 80,
                            ReceivedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 14,
                            BatchCode = "B-SP014-A",
                            ExpiryDate = new DateTime(2026, 9, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            ManufactureDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = 14,
                            Quantity = 120,
                            ReceivedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 15,
                            BatchCode = "B-SP015-A",
                            ExpiryDate = new DateTime(2026, 9, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            ManufactureDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = 15,
                            Quantity = 60,
                            ReceivedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 16,
                            BatchCode = "B-SP016-A",
                            ExpiryDate = new DateTime(2026, 9, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            ManufactureDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = 16,
                            Quantity = 180,
                            ReceivedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 17,
                            BatchCode = "B-SP017-A",
                            ExpiryDate = new DateTime(2026, 9, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            ManufactureDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = 17,
                            Quantity = 100,
                            ReceivedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 18,
                            BatchCode = "B-SP018-A",
                            ExpiryDate = new DateTime(2026, 9, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            ManufactureDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = 18,
                            Quantity = 140,
                            ReceivedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Website_QuanLyKhoHangThucPham.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<decimal>("CostPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MinStockLevel")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SKU")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("SellPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SKU")
                        .IsUnique()
                        .HasFilter("[SKU] IS NOT NULL");

                    b.HasIndex("SupplierId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CostPrice = 8000m,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MinStockLevel = 20,
                            Name = "Rau muong tuoi",
                            SKU = "SP001",
                            SellPrice = 12000m,
                            SupplierId = 1,
                            Unit = "kg"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CostPrice = 15000m,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MinStockLevel = 15,
                            Name = "Ca chua bi do",
                            SKU = "SP002",
                            SellPrice = 22000m,
                            SupplierId = 2,
                            Unit = "kg"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            CostPrice = 10000m,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MinStockLevel = 20,
                            Name = "Bap cai xanh",
                            SKU = "SP003",
                            SellPrice = 15000m,
                            SupplierId = 1,
                            Unit = "kg"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            CostPrice = 25000m,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MinStockLevel = 10,
                            Name = "Chuoi tieu",
                            SKU = "SP004",
                            SellPrice = 35000m,
                            SupplierId = 2,
                            Unit = "nai"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            CostPrice = 40000m,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MinStockLevel = 10,
                            Name = "Xoai cat Hoa Loc",
                            SKU = "SP005",
                            SellPrice = 58000m,
                            SupplierId = 2,
                            Unit = "kg"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            CostPrice = 130000m,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MinStockLevel = 10,
                            Name = "Thit heo ba chi tuoi",
                            SKU = "SP006",
                            SellPrice = 160000m,
                            SupplierId = 1,
                            Unit = "kg"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            CostPrice = 180000m,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MinStockLevel = 5,
                            Name = "Tom su tuoi",
                            SKU = "SP007",
                            SellPrice = 230000m,
                            SupplierId = 3,
                            Unit = "kg"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            CostPrice = 120000m,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MinStockLevel = 5,
                            Name = "Ca phi le dong lanh",
                            SKU = "SP008",
                            SellPrice = 155000m,
                            SupplierId = 3,
                            Unit = "kg"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            CostPrice = 28000m,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MinStockLevel = 30,
                            Name = "Trung ga tuoi (vi 10)",
                            SKU = "SP009",
                            SellPrice = 38000m,
                            SupplierId = 1,
                            Unit = "vi"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 4,
                            CostPrice = 28000m,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MinStockLevel = 50,
                            Name = "Sua tuoi Vinamilk 1L",
                            SKU = "SP010",
                            SellPrice = 36000m,
                            SupplierId = 4,
                            Unit = "hop"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 4,
                            CostPrice = 42000m,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MinStockLevel = 20,
                            Name = "Pho mai Con Bo Cuoi",
                            SKU = "SP011",
                            SellPrice = 56000m,
                            SupplierId = 4,
                            Unit = "goi"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 5,
                            CostPrice = 35000m,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MinStockLevel = 30,
                            Name = "Ca hoi dong hop",
                            SKU = "SP012",
                            SellPrice = 48000m,
                            SupplierId = 3,
                            Unit = "hop"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 6,
                            CostPrice = 85000m,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MinStockLevel = 20,
                            Name = "Gao ST25 5kg",
                            SKU = "SP013",
                            SellPrice = 110000m,
                            SupplierId = 2,
                            Unit = "tui"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 6,
                            CostPrice = 65000m,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MinStockLevel = 15,
                            Name = "Hat dieu rang muoi 200g",
                            SKU = "SP014",
                            SellPrice = 90000m,
                            SupplierId = 2,
                            Unit = "goi"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 7,
                            CostPrice = 210000m,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MinStockLevel = 20,
                            Name = "Nuoc ngot Pepsi 24 lon",
                            SKU = "SP015",
                            SellPrice = 265000m,
                            SupplierId = 5,
                            Unit = "thung"
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 8,
                            CostPrice = 25000m,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MinStockLevel = 30,
                            Name = "Nuoc mam Chinsu 500ml",
                            SKU = "SP016",
                            SellPrice = 33000m,
                            SupplierId = 1,
                            Unit = "chai"
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 8,
                            CostPrice = 38000m,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MinStockLevel = 25,
                            Name = "Dau an Tuong An 1L",
                            SKU = "SP017",
                            SellPrice = 50000m,
                            SupplierId = 1,
                            Unit = "chai"
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 6,
                            CostPrice = 18000m,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MinStockLevel = 30,
                            Name = "Bot mi Da Lat 1kg",
                            SKU = "SP018",
                            SellPrice = 25000m,
                            SupplierId = 2,
                            Unit = "goi"
                        });
                });

            modelBuilder.Entity("Website_QuanLyKhoHangThucPham.Models.RolePermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PermissionId = 1,
                            RoleName = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            PermissionId = 2,
                            RoleName = "Admin"
                        },
                        new
                        {
                            Id = 3,
                            PermissionId = 3,
                            RoleName = "Admin"
                        },
                        new
                        {
                            Id = 4,
                            PermissionId = 4,
                            RoleName = "Admin"
                        },
                        new
                        {
                            Id = 5,
                            PermissionId = 5,
                            RoleName = "Admin"
                        },
                        new
                        {
                            Id = 6,
                            PermissionId = 6,
                            RoleName = "Admin"
                        },
                        new
                        {
                            Id = 7,
                            PermissionId = 7,
                            RoleName = "Admin"
                        },
                        new
                        {
                            Id = 8,
                            PermissionId = 8,
                            RoleName = "Admin"
                        },
                        new
                        {
                            Id = 9,
                            PermissionId = 9,
                            RoleName = "Admin"
                        },
                        new
                        {
                            Id = 10,
                            PermissionId = 10,
                            RoleName = "Admin"
                        },
                        new
                        {
                            Id = 11,
                            PermissionId = 11,
                            RoleName = "Admin"
                        },
                        new
                        {
                            Id = 12,
                            PermissionId = 12,
                            RoleName = "Admin"
                        },
                        new
                        {
                            Id = 13,
                            PermissionId = 13,
                            RoleName = "Admin"
                        },
                        new
                        {
                            Id = 14,
                            PermissionId = 14,
                            RoleName = "Admin"
                        },
                        new
                        {
                            Id = 15,
                            PermissionId = 15,
                            RoleName = "Admin"
                        },
                        new
                        {
                            Id = 16,
                            PermissionId = 6,
                            RoleName = "WarehouseStaff"
                        },
                        new
                        {
                            Id = 17,
                            PermissionId = 7,
                            RoleName = "WarehouseStaff"
                        },
                        new
                        {
                            Id = 18,
                            PermissionId = 8,
                            RoleName = "WarehouseStaff"
                        },
                        new
                        {
                            Id = 19,
                            PermissionId = 9,
                            RoleName = "WarehouseStaff"
                        },
                        new
                        {
                            Id = 20,
                            PermissionId = 10,
                            RoleName = "WarehouseStaff"
                        },
                        new
                        {
                            Id = 21,
                            PermissionId = 11,
                            RoleName = "WarehouseStaff"
                        },
                        new
                        {
                            Id = 22,
                            PermissionId = 13,
                            RoleName = "WarehouseStaff"
                        },
                        new
                        {
                            Id = 23,
                            PermissionId = 6,
                            RoleName = "SalesStaff"
                        },
                        new
                        {
                            Id = 24,
                            PermissionId = 11,
                            RoleName = "SalesStaff"
                        },
                        new
                        {
                            Id = 25,
                            PermissionId = 12,
                            RoleName = "SalesStaff"
                        });
                });

            modelBuilder.Entity("Website_QuanLyKhoHangThucPham.Models.StoreOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerEmail")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CustomerName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CustomerPhone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DeliveryAddress")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Note")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("OrderCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TransactionRef")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("OrderCode")
                        .IsUnique();

                    b.ToTable("StoreOrders");
                });

            modelBuilder.Entity("Website_QuanLyKhoHangThucPham.Models.StoreOrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("StoreOrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("StoreOrderId");

                    b.ToTable("StoreOrderItems");
                });

            modelBuilder.Entity("Website_QuanLyKhoHangThucPham.Models.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Code")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ContactPerson")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Suppliers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "SACH01",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "sach@viet.vn",
                            IsActive = true,
                            Name = "Cong ty Thuc pham Sach Viet",
                            Phone = "0901234567"
                        },
                        new
                        {
                            Id = 2,
                            Code = "MEK02",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "mek@delta.vn",
                            IsActive = true,
                            Name = "Cong ty Nong San Mekong",
                            Phone = "0912345678"
                        },
                        new
                        {
                            Id = 3,
                            Code = "BD03",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "bd@bien.vn",
                            IsActive = true,
                            Name = "Cong ty Hai San Bien Dong",
                            Phone = "0923456789"
                        },
                        new
                        {
                            Id = 4,
                            Code = "VNM04",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "vn@milk.vn",
                            IsActive = true,
                            Name = "Vinamilk Distribution",
                            Phone = "1800123456"
                        },
                        new
                        {
                            Id = 5,
                            Code = "SAB05",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "sab@eco.vn",
                            IsActive = true,
                            Name = "Sabeco Trading",
                            Phone = "0934567890"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Website_QuanLyKhoHangThucPham.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Website_QuanLyKhoHangThucPham.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Website_QuanLyKhoHangThucPham.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Website_QuanLyKhoHangThucPham.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Website_QuanLyKhoHangThucPham.Models.ExportRequest", b =>
                {
                    b.HasOne("Website_QuanLyKhoHangThucPham.Models.ApplicationUser", "ProcessedBy")
                        .WithMany()
                        .HasForeignKey("ProcessedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Website_QuanLyKhoHangThucPham.Models.ApplicationUser", "RequestedBy")
                        .WithMany()
                        .HasForeignKey("RequestedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ProcessedBy");

                    b.Navigation("RequestedBy");
                });

            modelBuilder.Entity("Website_QuanLyKhoHangThucPham.Models.ExportRequestDetail", b =>
                {
                    b.HasOne("Website_QuanLyKhoHangThucPham.Models.ExportRequest", "ExportRequest")
                        .WithMany("Details")
                        .HasForeignKey("ExportRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Website_QuanLyKhoHangThucPham.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Website_QuanLyKhoHangThucPham.Models.Product", null)
                        .WithMany("ExportDetails")
                        .HasForeignKey("ProductId1");

                    b.Navigation("ExportRequest");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Website_QuanLyKhoHangThucPham.Models.ImportReceipt", b =>
                {
                    b.HasOne("Website_QuanLyKhoHangThucPham.Models.ApplicationUser", "ConfirmedBy")
                        .WithMany()
                        .HasForeignKey("ConfirmedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Website_QuanLyKhoHangThucPham.Models.ApplicationUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Website_QuanLyKhoHangThucPham.Models.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Website_QuanLyKhoHangThucPham.Models.Supplier", null)
                        .WithMany("ImportReceipts")
                        .HasForeignKey("SupplierId1");

                    b.Navigation("ConfirmedBy");

                    b.Navigation("CreatedBy");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("Website_QuanLyKhoHangThucPham.Models.ImportReceiptDetail", b =>
                {
                    b.HasOne("Website_QuanLyKhoHangThucPham.Models.ImportReceipt", "ImportReceipt")
                        .WithMany("Details")
                        .HasForeignKey("ImportReceiptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Website_QuanLyKhoHangThucPham.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Website_QuanLyKhoHangThucPham.Models.Product", null)
                        .WithMany("ImportDetails")
                        .HasForeignKey("ProductId1");

                    b.Navigation("ImportReceipt");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Website_QuanLyKhoHangThucPham.Models.InventoryBatch", b =>
                {
                    b.HasOne("Website_QuanLyKhoHangThucPham.Models.Product", "Product")
                        .WithMany("Batches")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Website_QuanLyKhoHangThucPham.Models.Product", b =>
                {
                    b.HasOne("Website_QuanLyKhoHangThucPham.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Website_QuanLyKhoHangThucPham.Models.Supplier", "Supplier")
                        .WithMany("Products")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("Website_QuanLyKhoHangThucPham.Models.RolePermission", b =>
                {
                    b.HasOne("Website_QuanLyKhoHangThucPham.Models.AppPermission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");
                });

            modelBuilder.Entity("Website_QuanLyKhoHangThucPham.Models.StoreOrderItem", b =>
                {
                    b.HasOne("Website_QuanLyKhoHangThucPham.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Website_QuanLyKhoHangThucPham.Models.StoreOrder", "Order")
                        .WithMany("Items")
                        .HasForeignKey("StoreOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Website_QuanLyKhoHangThucPham.Models.AppPermission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("Website_QuanLyKhoHangThucPham.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Website_QuanLyKhoHangThucPham.Models.ExportRequest", b =>
                {
                    b.Navigation("Details");
                });

            modelBuilder.Entity("Website_QuanLyKhoHangThucPham.Models.ImportReceipt", b =>
                {
                    b.Navigation("Details");
                });

            modelBuilder.Entity("Website_QuanLyKhoHangThucPham.Models.Product", b =>
                {
                    b.Navigation("Batches");

                    b.Navigation("ExportDetails");

                    b.Navigation("ImportDetails");
                });

            modelBuilder.Entity("Website_QuanLyKhoHangThucPham.Models.StoreOrder", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Website_QuanLyKhoHangThucPham.Models.Supplier", b =>
                {
                    b.Navigation("ImportReceipts");

                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
